### ISSUE TITLE
Where are Cristals?

### ISSUE THREAD

**Issue by Gab304** [UnionofSovietSocialistRepublics/Spore-Biomechs#10]
the mineral "cristal" is in all maps or just in the ones added my the mod?

**Comment by Gab304** [comment]
I can't find them on any map

**Comment by UnionofSovietSocialistRepublics** [comment]
Seem kind of weird, crystal can generate in custom map but not campaign

**Comment by Gab304** [comment]
and but in the tech tree to unlock the mass cultivator it asks me to "discover the crystals"

**Comment by UnionofSovietSocialistRepublics** [comment]
added a custom map for it, sorry for forcing to wait this long
