### ISSUE TITLE
why is breacher so op

### ISSUE THREAD

**Issue by ErosAa2** [UnionofSovietSocialistRepublics/Spore-Biomechs#5]
y know it somehow shreds late game units with high dps. Maybe you forgot to balance that?
(tbf kinda sucked when my behomoths died to these during a pvp session)
![Screenshot (102)](https://user-images.githubusercontent.com/113437785/210131192-0c12599d-a600-440f-b1ac-072d63dfc70e.png)

**Comment by UnionofSovietSocialistRepublics** [comment]
nerfed the fuse, Im sure that will work

**Comment by UnionofSovietSocialistRepublics** [comment]
done nerfing it to the ground
still able to kill behomoth
thats why lobber exists h
