### ISSUE TITLE
Where is Biomass Processor on tech tree?

### ISSUE THREAD

**Issue by Dshadeslayer** [UnionofSovietSocialistRepublics/Spore-Biomechs#6]
I do not think it's shown up, unless I'm missing a mission completed to be able to see it.

**Comment by UnionofSovietSocialistRepublics** [comment]
done being dead, this issue is fixed a while ago

**Comment by Dshadeslayer** [comment]
Man, that doesn't help the issue. Where should it be in the tree? What's the prerequisite tech or such? I haven't even been able to test this mod due to this.

**Comment by Dshadeslayer** [comment]
![Uploading Screenshot_20230130-171006_Mindustry.jpg…]()

**Comment by UnionofSovietSocialistRepublics** [comment]
Okay, fixed (For real this time)
